### ISSUE TITLE
WriteAttribute not found

### ISSUE THREAD

**Issue by mikecg** [RazorGenerator/RazorGenerator#46] opened 2015-09-03 16:01 UTC
The generated.cs files being generated by the VS 2015 extension (1.9.1) reference a WriteAttribute method, but the method cannot be found, so the build fails.

The same cshtml files using the extension in VS 2013 (Version 1.2) generate generated.cs files which do not make use of the WriteAttribute method, and these cs files build fine.

It appears that something broke between Version 1.2 and Version 1.9.1, or I have some incorrect dependencies or config. 

Can I use version 1.2 in VS 2015? Any thoughts?

**Comment by davidebbo** [comment] 2015-09-03 18:23
Can you please give more details about your scenario? There are many different ways of using RazorGenerator. e.g. using msbuild time or not, using it for MVC, for general templates, ...

**Comment by mikecg** [comment] 2015-09-03 21:08
Hi David,

Thanks for getting back to me so quickly! I'd be happy to give you more information.

By the way, the tool has been working great thus far. Thank you for creating it and maintaining it!

I use the tool to generate HTML for sending e-mails. There are currently 4 cshtml templates in my solution configured to use RazorGenerator. Each of them has the following headers, which I think means that I use it for general templates:
```cs
@* Generator : Template TypeVisibility : Internal GeneratePrettyNames : true *@
@using Some.NameSpace
@using Some.OtherNameSpace
@functions {
    public SomeType Model { get; set; }
}
```

As I mentioned in my original post, the RazorGenerator extension installed in VS 2013 generates cs files with no errors, however, the extension in VS 2015 creates errors.

For example, in VS 2013, this line is generated:
```cs
WriteLiteral("/styles/images/spacer.png\" alt=\" \" width=\"80\" height=\"80\" />-->\r\n            <a s" +
"tyle=\"padding-left: 80px\" href=\"");
```

In VS 2015, the equivalent line is generated as follows instead:
```cs
WriteLiteral("/styles/images/spacer.png\" alt=\" \" width=\"80\" height=\"80\" />-->\r\n            <a");
WriteLiteral(" style=\"padding-left: 80px\"");
WriteAttribute("href", Tuple.Create(" href=\"", 1340), Tuple.Create("\"", 1367)
```

`WriteAttribute` does not exist in `RazorTemplateBase`, so compilation fails.

I am not very experienced with Razor, so I am not familiar with all the various use cases and configuration options. Please let me know if there is any other specific info I can provide you.

Thanks,
Mike

**Comment by davidebbo** [comment] 2015-09-03 21:16
Make sure that you are using the latest version of the `RazorGenerator.Templating` nuget package, which is 2.3.9. See https://www.nuget.org/packages/RazorGenerator.Templating/.

**Comment by davidebbo** [comment] 2015-09-03 21:27
Actually, I was thinking about the change @atifaziz made, but that added `WriteLiteralTo` and not `WriteAttribute`.

Though I'm confused about your repro. How can the generated code contain references to `/styles/images/spacer.png`, when your template has no such thing? Is the template you showed incomplete?

**Comment by atifaziz** [comment] 2015-09-03 23:11
I believe `WriteAttribute` only comes in effect when Razor v2 and v3 are being used. See [`TemplateTest.txt` for v1](https://github.com/RazorGenerator/RazorGenerator/blob/ca7a2917722663a5c1517c648dd5549609d9973d/RazorGenerator.Core.Test/TestFiles/Output_v1/TemplateTest.txt#L40) vs [`TestTemplate.txt` for v2](https://github.com/RazorGenerator/RazorGenerator/blob/ca7a2917722663a5c1517c648dd5549609d9973d/RazorGenerator.Core.Test/TestFiles/Output_v2/TemplateTest.txt#L35). And yes, [`RazorTemplateBase.cs`](https://github.com/RazorGenerator/RazorGenerator/blob/ca7a2917722663a5c1517c648dd5549609d9973d/RazorGenerator.Templating/RazorTemplateBase.cs) is indeed missing when v2 and v3 are generating the code. This issue must have been around long before I introduced enhancements for generic type parameters. The real question is really why using 1.9.1 in VS 2015 is causing v2/3 to be picked up for @mikecg.

**Comment by davidebbo** [comment] 2015-09-03 23:20
I see. Well, regardless of that mystery, it sounds like adding `WriteAttribute` to `RazorTemplateBase` would probably be a good thing.

**Comment by atifaziz** [comment] 2015-09-04 05:32
@davidebbo Agreed. Also my hunch is that PR #45 may have introduced a regression as it toyed with Razor engine version selection, which is the major change that went into 1.9.1. Then again, the real culprit could be anywhere between 1.2 and 1.9.1.

**Comment by atifaziz** [comment] 2015-09-04 11:03
@mikecg A workaround for this issue currently is to lock the Razor runtime version to 1.0 explicitly (and which might be a good thing anyhow) via the `RazorVersion` directive:

```
@* Generator : Template 
   TypeVisibility : Internal 
   GeneratePrettyNames : true 
   RazorVersion : 1 *@
```

**Comment by mikecg** [comment] 2015-09-04 13:38
Hi Everyone

@davidebbo Regarding your confusion about `/styles/images/spacer.png`, you are correct that I did not post the entire template - I only posted the headers.

Thank you for the workaround. It works! I had a feeling the issue had something to do with the version of Razor being used by the generator, but I wasn't sure how to set the version explicitly. 

The main GitHub page states
> Version 1.5 of the VSIX adds support for Razor 2.0 syntax. It auto detects whether it should use 1.0 or 2.0 based on the assembly being referenced by the project.

so I downgraded AspNet.Razor from 3 to 2, suspecting that would fix it, but I still had the issue. I didn't try going from 2 to 1 as I ran out of time to keep playing around with it.

Thanks again. I appreciate the quick turnaround time.

**Comment by davidebbo** [comment] 2015-09-04 23:50
@atifaziz I think you may be right about the last change being related to this. /cc @jtheisen.

Let's keep this issue open to track that we should add `WriteAttribute` to the based template at some point.

**Comment by jtheisen** [comment] 2015-09-05 10:55
Previous to the change I made, the engine would always be v1 when a generator was specified and the version detection mechanism wasn't used at all (which is wrong). If the change breaks things for people now it suggests that the version detection mechanism has had another, unrelated bug.

**Comment by atifaziz** [comment] 2015-09-05 18:31
@davidebbo The [implementation of `WriteAttribute` & `WriteAttributeTo`](https://github.com/RazorGenerator/RazorGenerator/commit/e7a88dcb7bd6f2c8a87649c1f2e3e3d63e649d63#diff-c886ab4c2bba04ffb942d6251e2edf77R94) turned out quite bulky but it doesn't seem there's much choice given how Razor generates code, encoding attribute bits as nested tuples. Happy if you can review and close this issue if you don't see any problems.

**Comment by davidebbo** [comment] 2015-09-06 16:56
@atifaziz Nice! What code did you use as a basis? It's similar yet in various ways different from the `WebPageExecutingBase` sources (https://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.WebPages/WebPageExecutingBase.cs). Though either way is probably fine, especially since we have no implementation at all right now :)

**Comment by atifaziz** [comment] 2015-09-06 18:10
@davidebbo Yes, I used the algorithm from `WebPageExecutingBase` for sake of compatibility and least element of surprise, as I [also pointed out in the code](https://github.com/RazorGenerator/RazorGenerator/blob/e7a88dcb7bd6f2c8a87649c1f2e3e3d63e649d63/RazorGenerator.Templating/RazorTemplateBase.cs#L109-L112), and then adapted it to deal directly with the incoming tuples. `WebPageExecutingBase` does it slightly differently using [helper][AttributeValue] [types][PositionTagged] that I didn't want to introduce to bloat the code. Those types certainly make the tuples palatable but would add very little value otherwise.

I did find some funny cases in the way `WebPageExecutingBase` renders attributes but that's something that can be improved and revisited later. For now, it's at least compatible and no worse than what the published version is doing.

  [AttributeValue]: (https://github.com/ASP-NET-MVC/aspnetwebstack/blob/66298100f4e349d3812b1aad32c5278c256a2cdd/src/System.Web.WebPages/AttributeValue.cs)
  [PositionTagged]: https://github.com/ASP-NET-MVC/aspnetwebstack/blob/66298100f4e349d3812b1aad32c5278c256a2cdd/src/System.Web.WebPages/Instrumentation/PositionTagged.cs

**Comment by davidebbo** [comment] 2015-09-08 19:08
Ok, I just pushed RazorGenerator.Templating version 2.3.11 to NuGet. @mikecg can you please give it a try? @atifaziz thanks for the fix!

**Closed by davidebbo** 2015-09-08 19:08 UTC

**Comment by mikecg** [comment] 2015-09-08 20:38
@davidebbo I updated the nuget package, remove the ```RazorVersion : 1``` header, and reran the tool. The generated generated.cs now compiles with no errors.

Thanks!

**Comment by davidebbo** [comment] 2015-09-08 20:40
@mikecg Compiles and runs well too? :)

**Comment by mikecg** [comment] 2015-09-09 13:41
All works splendidly.

**Comment by gandarez** [comment] 2016-06-17 13:22
Hey folks,

I'm having the same strange issue even with the latest libraries installed.
![image](https://cloud.githubusercontent.com/assets/782854/16151651/900153a8-3474-11e6-8a2f-e4882d067e28.png)

**.chtml**
```C#
@* Generator: Template
    TypeVisibility: Internal
    GeneratePrettyNames: true    
    Imports: System.IO
    Namespace: Hangfire.Dashboard.Pages
*@
```
```HTML
<tr class="js-jobs-list-row hover">
    <td>
        <input type="checkbox" class="js-jobs-list-checkbox" name="jobs[]" value="@job.Id" />
    </td>
    <td class="min-width">@job.Id</td>
    <td>
        @job.Queue
    </td>
</tr>
```

**generated**
```C#
WriteLiteral(" class=\"js-jobs-list-row hover\"");

WriteLiteral(">\r\n                                <td>\r\n                                    <inp" +
"ut");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"js-jobs-list-checkbox\"");

WriteLiteral(" name=\"jobs[]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3773), Tuple.Create("\"", 3788)
            
            #line 98 "..\..\Views\Loaded\LoadedJobspage.cshtml"
                              , Tuple.Create(Tuple.Create("", 3781), Tuple.Create<System.Object, System.Int32>(job.Id
            
            #line default
            #line hidden
, 3781), false)
);

WriteLiteral(" />\r\n                                </td>\r\n                                <td");

WriteLiteral(" class=\"min-width\"");
```
![image](https://cloud.githubusercontent.com/assets/782854/16151779/317eadd4-3475-11e6-8493-7ee4cb52d838.png)

If I change as suggested above to ```RazorVersion : 1``` works like a charm. Any thoughts?

**Comment by pranavkm** [comment] 2016-06-17 14:38
What's the base class on your generated type? `WriteAttribute` exists on `RazorTemplateBase`: https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Templating/RazorTemplateBase.cs#L96

**Comment by gandarez** [comment] 2016-06-17 19:49
@pranavkm It's `RazorPage`.

**Comment by pranavkm** [comment] 2016-06-17 19:50
That's odd - aren't you generating templates: `Generator: Template`?

**Comment by gandarez** [comment] 2016-06-17 20:02
@pranavkm here's the full header
```C#
@*
    Generator: Template
    TypeVisibility: Internal
    GeneratePrettyNames: true
    Namespace: Hangfire.Dashboard.Pages
    RazorVersion : 1
*@
```

**Comment by pranavkm** [comment] 2016-06-18 00:51
The `RazorVersion` token is throwing the engine off. Remove it and you should get types deriving from `RazorTemplateBase`.

**Comment by gandarez** [comment] 2016-06-20 13:34
@pranavkm I can't do that because my view must inherit from `RazorPage`

```
@inherits RazorPage
```

**Comment by mojk** [comment] 2019-07-24 09:30
> @pranavkm I can't do that because my view must inherit from `RazorPage`
> 
> ```
> @inherits RazorPage
> ```

Having the exact same issue, did you solve it somehow?

**Comment by Jehoel** [comment] 2019-08-26 04:08
@mojk Can you post your problem as a new GitHub Issue because a lot has changed since 2015 when this question was first raised and there can be other reasons for that error message.

**Comment by mojk** [comment] 2019-08-26 07:14
> @mojk Please post your problem as a new GitHub Issue because a lot has changed since 2015 when this question was first raised and there can be other reasons for that error message.

I managed to solve it! The project that I was trying to extend used an older version, so by simply using RazorVersion: 1, it worked.
