### ISSUE TITLE
Dynamic Load Issues

### ISSUE THREAD

**Issue by pyromanci** [RazorGenerator/RazorGenerator#14] opened 2015-05-07 15:42 UTC
So I have a Intializer class in my Main site:
```c#
    public static class Initializer
    {
        public static void Initialize()
        {
            var pluginFolder = new DirectoryInfo(HostingEnvironment.MapPath("~/Plugins"));
            var pluginAssemblyFiles = pluginFolder.GetFiles("*.dll", SearchOption.AllDirectories);
            foreach (var pluginAssemblyFile in pluginAssemblyFiles)
            {
                var asm = Assembly.LoadFrom(pluginAssemblyFile.FullName);
                BuildManager.AddReferencedAssembly(asm);
            }
        }
    }
```

When I create a DLL with precompiled views and reference it in the main site (so it's in the bin folder). I can get it to work just fine. However when I put it in the Plugins folder and let it get references at runtime, it does not work and throws the follwoing:
The view 'Index' or its master was not found or no view engine supports the searched locations. The following locations were searched:
```c#
~/Views/Dynamicplugin/Index.cshtml
~/Views/Shared/Index.cshtml
~/Views/Dynamicplugin/Index.aspx
~/Views/Dynamicplugin/Index.ascx
~/Views/Shared/Index.aspx
~/Views/Shared/Index.ascx
~/Views/Dynamicplugin/Index.vbhtml
~/Views/Shared/Index.vbhtml
```

My only guess is it has something to do with the RazorGeneratorMvcStart class. Potentially the 
```c#
[assembly: WebActivatorEx.PostApplicationStartMethod(typeof(SmartWeb.Plugin.DynamicPlugin.App_Start.RazorGeneratorMvcStart), "Start")]
```
line in that file.

Anyone have a clue how to to fix this?

**Comment by davidebbo** [comment] 2015-05-08 02:10
I think the issue is not really related to RazorGenerator, but to WebActivatorEx, which only processes `bin` assemblies. Maybe we can fix WebActivatorEx to call `BuildManager.GetReferencedAssemblies()`. Here is the [current code](https://github.com/davidebbo/WebActivator/blob/7865ee0f69b8a7118548162e5a92c1202d1ca8fc/WebActivator/ActivationManager.cs#L100-L108).

**Comment by pyromanci** [comment] 2015-05-08 12:29
Well, that could work, but how will you get around that the `BuildManager.GetReferencedAssemblies()` can not be called in the pre-start initialization?

**Comment by davidebbo** [comment] 2015-05-08 14:06
You're right, now I remember that it's probably the reason it doesn't call that!

Another possible option is to register the plugin assemblies' view engines explicitly from the same place where you load them.

I guess ideally WebActivator would have a method where you just pass it one Assembly and it adds it to its list.

**Comment by pyromanci** [comment] 2015-05-14 18:58
So I took your recommendation and played with the loading code some. and can up with this:
```c#
            var pluginFolder = new DirectoryInfo(HostingEnvironment.MapPath("~/Plugins"));
            var pluginAssemblyFiles = pluginFolder.GetFiles("*.dll", SearchOption.AllDirectories);
            foreach (var pluginAssemblyFile in pluginAssemblyFiles)
            {
                var asm = Assembly.LoadFrom(pluginAssemblyFile.FullName);
                BuildManager.AddReferencedAssembly(asm);

                var type = asm.GetExportedTypes().Where(x => x.Name == "RazorGeneratorMvcStart").SingleOrDefault();
                var engine = new PrecompiledMvcEngine(type.Assembly);

                if (HttpContext.Current != null)
                    engine.UsePhysicalViewsIfNewer = HttpContext.Current.Request.IsLocal;

                ViewEngines.Engines.Insert(0, engine);

                // StartPage lookups are done by WebPages. 
                VirtualPathFactoryManager.RegisterVirtualPathFactory(engine);
            }
```

I was able to get the precompiled controller to load without problems with that.

**Comment by davidebbo** [comment] 2015-05-14 19:14
I don't quite get your logic. I looks like:

1. you have the Assembly
2. you find a Type within that assembly
3. you use that Type to then get right back at the Assembly.

Aren't you just getting back what you already had in step 1?

**Comment by pyromanci** [comment] 2015-05-14 19:20
I don't understand it my self, but when i use the `asm` assembly it fails to render., but when i grab the type then the assembly it works.

**Comment by davidebbo** [comment] 2015-05-14 19:22
Puzzling! Oh well, I'll close this one since you seem to be in good shape now.

**Closed by davidebbo** 2015-05-14 19:22 UTC
